apiVersion: v1
kind: Pod
metadata:
  name: alpine-client
  labels:
    app: myapplabel
spec:  # specification of the pod's contents
  restartPolicy: Always
  containers:
  - name: alpine-01
    image: "node:14.17.5-alpine3.14"
    # Just spin & wait forever
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
