apiVersion: v1
kind: Pod
metadata:
  name: centos-client
  labels:
    app: myapplabel
spec:  # specification of the pod's contents
  restartPolicy: Always
  containers:
  - name: centos-01
    image: "centos:centos7"
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
