apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couchbase
  labels:
    app: couchbase
    release: prometheus
spec:
  jobLabel: couchbase
  selector:
    matchLabels:
      app: couchbase
  namespaceSelector:
    matchNames:
    - cbdb
  endpoints:
  - port: metrics
    interval: 5s
