apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: pgeDemo
  region: us-west-2
  version: '1.18'
availabilityZones:
    - us-west-2a
    - us-west-2b
# traits of worker nodes
nodeGroups:
  - name: m5l-workers
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    ami: auto
    iam:
      # polices added to worker node role
      withAddonPolicies:
        # allows read/write to zones in Route53
        externalDNS: true
        # required for ALB-ingress
        albIngress: true
  - name: r5l-workers
    instanceType: r5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    ami: auto
    iam:
      # polices added to worker node role
      withAddonPolicies:
        # allows read/write to zones in Route53
        externalDNS: true
        # required for ALB-ingress
        albIngress: true
  - name: t2xl-workers
    instanceType: t2.xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    ami: auto
    iam:
      # polices added to worker node role
      withAddonPolicies:
        # allows read/write to zones in Route53
        externalDNS: true
        # required for ALB-ingress
        albIngress: true
