apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: blue
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.3
  antiAffinity: true
#  tls:
#    static:
#      member:
#        serverSecret: couchbase-server-tls
#      operatorSecret: couchbase-operator-tls
  authSecret: cb-example-auth
  exposeAdminConsole: true
  adminConsoleServiceType: NodePort
  adminConsoleServices:
    - data
  exposedFeatures:
    - xdcr
    - client
  exposedFeatureServiceType: NodePort
#  dns:
#    domain: domain.com
  cluster:
    dataServiceMemoryQuota: 1024
    indexServiceMemoryQuota: 1024
    searchServiceMemoryQuota: 1024
    eventingServiceMemoryQuota: 1024
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: plasma
    autoFailoverTimeout: 10
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 60
    autoFailoverServerGroup: false
  #buckets:
  #  - name: default
  #    type: couchbase
  #    memoryQuota: 128
  #    replicas: 1
  #    ioPriority: high
  #    evictionPolicy: valueOnly
  #    conflictResolution: seqno
  #    enableFlush: true
  #    enableIndexReplica: false
  #    compressionMode: passive
  servers:
    - name: data-east-1a
      size: 1
      services:
        - data
        - query
        - index
      serverGroups:
       - us-east-1a
      pod:
        volumeMounts:
          default: pvc-default 	# /opt/couchbase/var/lib/couchbase
          data: pvc-data	# /mnt/data
          index: pvc-index
    - name: data-east-1b
      size: 1
      services:
        - data
        - query
        - index
      serverGroups:
       - us-east-1b
      pod:
        volumeMounts:
          default: pvc-default
          data: pvc-data
          index: pvc-index
    - name: data-east-1c
      size: 1
      services:
        - data
        - query
        - index
      serverGroups:
       - us-east-1c
      pod:
        volumeMounts:
          default: pvc-default
          data: pvc-data
          index: pvc-index

  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 1000
  disableBucketManagement: true
  volumeClaimTemplates:
    - metadata:
        name: pvc-default
      spec:
        storageClassName: gp2-multi-zone
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: pvc-data
      spec:
        storageClassName: gp2-multi-zone
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: pvc-index
      spec:
        storageClassName: gp2-multi-zone
        resources:
          requests:
            storage: 3Gi
