
# Default values for couchbase-cluster
cluster:
  platform: aws
  # name of the cluster. defaults to name of chart release
  name: demo
  # image is the base couchbase image and version of the couchbase cluster
  image: "couchbase/server:6.6.1"
  # guarantees that the pods in the same cluster are unable to be scheduled on the same node
  antiAffinity: true
  upgradeStrategy: RollingUpgrade
  hibernate: false
  hibernationStrategy: Immediate
  recoveryPolicy: PrioritizeDataIntegrity
  security:
    adminSecret: cb-admin-auth
    rbac:
      managed: false
    # ldap: {}
  # networking options
  networking:
    # Option to expose admin console
    exposeAdminConsole: true
    # Option to expose admin console
    adminConsoleServices:
      - data
    # Specific services to use when exposing ui
    exposedFeatures:
      - client
      - xdcr
    # Defines how the admin console service is exposed.
    # Allowed values are NodePort and LoadBalancer.
    # If this field is LoadBalancer then you must also define a spec.dns.domain.
    adminConsoleServiceType: LoadBalancer
    # Defines how the per Couchbase node ports are exposed.
    # Allowed values are NodePort and LoadBalancer.
    # If this field is LoadBalancer then you must also define a spec.dns.domain.
    exposedFeatureServiceType: LoadBalancer
    # This controls routing to external services.
    exposedFeatureTrafficPolicy: Local
    # The Couchbase cluster tls configuration (auto-generated)
    tls:
      static:
        serverSecret: mojio-server-tls
        operatorSecret: mojio-operator-tls
    # The dynamic DNS configuration to use when exposing services
    dns:
      domain: cbdbdemo.com

    # Custom map of annotations to be added to console and per-pod (exposed feature) services
    exposedFeatureServiceTemplate:
      spec:
        type: LoadBalancer
    adminConsoleServiceTemplate:
      spec:
        type: LoadBalancer
  logging:
    # The retention period that log volumes are kept for after their associated pods have been deleted.
    logRetentionTime: 604800s
    # The maximum number of log volumes that can be kept after their associated pods have been deleted.
    logRetentionCount: 20
  # xdcr defines remote clusters and replications to them.
  xdcr:
    # managed defines whether the Operator should manage XDCR remote clusters
    managed: false
    # remoteClusters contains references to any remote clusters to replicate to
    # remoteClusters:
  # backup defines values for automated backup.
  backup:
    # managed determines whether Automated Backup is enabled
    managed: false
    # image used by the Operator to perform backup or restore
    # image: couchbase/operator-backup:6.6.0-102
    image: couchbase/operator-backup:1.0.0
    s3Secret: s3-cb-backup-secret-managed
    # optional service account to use when performing backups
    # service account will be created if it does not exist
    # serviceAccountName:
  # defines integration with third party monitoring sofware
  monitoring:
    prometheus:
      # defines whether Prometheus metric collection is enabled
      enabled: false
      # image used by the Operator to perform metric collection
      # (injected as a "sidecar" in each Couchbase Server Pod)
      image: couchbase/exporter:1.0.4
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          memory: 500Mi
          cpu: 500m
  # Cluster wide settings for nodes and services
  cluster:
    # The amount of memory that should be allocated to the data service
    dataServiceMemoryQuota: 1Gi
    # The amount of memory that should be allocated to the index service
    indexServiceMemoryQuota: 1Gi
    # The amount of memory that should be allocated to the search service
    searchServiceMemoryQuota: 1Gi
    # The amount of memory that should be allocated to the eventing service
    eventingServiceMemoryQuota: 1Gi
    # The amount of memory that should be allocated to the analytics service
    analyticsServiceMemoryQuota: 1Gi
    # The index storage mode to use for secondary indexing
    indexStorageSetting: plasma
    # Timeout that expires to trigger the auto failover.
    autoFailoverTimeout: 10s
    # The number of failover events we can tolerate
    autoFailoverMaxCount: 3
    # Whether to auto failover if disk issues are detected
    autoFailoverOnDataDiskIssues: true
    # Whether the cluster will automatically failover an entire server group
    autoFailoverServerGroup: true
    # How long to wait for transient errors before failing over a faulty disk
    autoFailoverOnDataDiskIssuesTimePeriod: 60s
    # configuration of global Couchbase auto-compaction settings.
    autoCompaction:
      # amount of fragmentation allowed in persistent database [2-100]
      databaseFragmentationThreshold:
        percent: 20
        size: 2Gi
      # amount of fragmentation allowed in persistent view files [2-100]
      viewFragmentationThreshold:
        percent: 20
        size: 2Gi
      # whether auto-compaction should be performed in parallel
      parallelCompaction: false
      timeWindow:
        start: 09:00
        end: 13:00
        abortCompactionOutsideWindow: true
      tombstonePurgeInterval: 72h

  # configuration of logging functionality
  # for use in conjuction with logs persistent volume mount
  logging:
    # retention period that log volumes are kept after pods have been deleted
    logRetentionTime: 604800s
    # the maximum number of log volumes that can be kept after pods have been deleted
    logRetentionCount: 20
  # kubernetes security context applied to pods
  securityContext:
    # fsGroup of persistent volume mount
    fsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
  # cluster buckets
  buckets:
    # Managed defines whether buckets are managed by us or the clients.
    managed: true
  enablePreviewScaling: false
  servers:
    # Name for the server configuration. It must be unique.
    default: null
    data:
      name: data-service
      # Size of the couchbase cluster.
      size: 1
      # The services to run on nodes
      services:
        - data
      # Defines whether Autoscale is permitted for this specific server configuration.
      # Only `query` service is allowed to be defined unless `enablePreviewScaling` is set.
      autoscaleEnabled: false
      # volume claims to use for persistent storage
      volumeMounts:
        default: pvc-default 	# /opt/couchbase/var/lib/couchbase
        data: pvc-data	      # /mnt/data
      # ServerGroups define the set of availability zones we want to distribute pods over.
      serverGroups:
        - us-west-2a
        - us-west-2b
        - us-west-2c
      resources:
        requests:
          cpu: 1000m
          memory: 3Gi
    # Name for the server configuration. It must be unique.
    index:
      # Size of the couchbase cluster.
      size: 1
      # The services to run on nodes
      services:
        - index
        - query
      # Defines whether Autoscale is permitted for this specific server configuration.
      # Only `query` service is allowed to be defined unless `enablePreviewScaling` is set.
      autoscaleEnabled: false
      # volume claims to use for persistent storage
      volumeMounts:
        default: pvc-default 	# /opt/couchbase/var/lib/couchbase
        index: pvc-index	      # /mnt/index
      # ServerGroups define the set of availability zones we want to distribute pods over.
      serverGroups:
        - us-west-2a
        - us-west-2b
        - us-west-2c
      resources:
        requests:
          cpu: 1000m
          memory: 3Gi
    # Name for the server configuration. It must be unique.
    # query:
    #   # Size of the couchbase cluster.
    #   size: 1
    #   # The services to run on nodes
    #   services:
    #     - query
    #   # Defines whether Autoscale is permitted for this specific server configuration.
    #   # Only `query` service is allowed to be defined unless `enablePreviewScaling` is set.
    #   autoscaleEnabled: false
    #   # volume claims to use for persistent storage
    #   volumeMounts:
    #     default: pvc-default 	# /opt/couchbase/var/lib/couchbase
    #   # ServerGroups define the set of availability zones we want to distribute pods over.
    #   serverGroups:
    #     - us-west-2a
    #     - us-west-2b
    #     - us-west-2c
    #   resources:
    #     requests:
    #       cpu: 1000m
    #       memory: 3Gi
    # # Tutorial on how-to use Analytics https://docs.couchbase.com/server/current/analytics/primer-beer.html
    # analytics:
    #   name: analytics-service
    #   # Size of the couchbase cluster.
    #   size: 3
    #   # The services to run on nodes
    #   services:
    #     - analytics
    #   # Defines whether Autoscale is permitted for this specific server configuration.
    #   # Only `query` service is allowed to be defined unless `enablePreviewScaling` is set.
    #   autoscaleEnabled: false
    #   # volume claims to use for persistent storage
    #   volumeMounts:
    #     default: pvc-default 	# /opt/couchbase/var/lib/couchbase
    #     analytics:
    #       - pvc-analytics	    # /mnt/analytics-00
    #       - pvc-analytics       # /mnt/analytics-01
    #   # ServerGroups define the set of availability zones we want to distribute pods over.
    #   serverGroups:
    #     - us-west-2a
    #     - us-west-2b
    #     - us-west-2c
    #   resources:
    #     requests:
    #       cpu: 1000m
    #       memory: 5Gi
  # VolumeClaimTemplates define the desired characteristics of a volume
  # that can be requested and claimed by a pod.
  volumeClaimTemplates:
    - metadata:
        name: pvc-default
      spec:
        storageClassName: gp2-multi-zone
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: pvc-analytics
      spec:
        storageClassName: gp2-multi-zone
        resources:
          requests:
            storage: 256Gi
    - metadata:
        name: pvc-data
      spec:
        storageClassName: gp2-multi-zone
        resources:
          requests:
            storage: 200Gi
    - metadata:
        name: pvc-index
      spec:
        storageClassName: gp2-multi-zone
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: pvc-log
      spec:
        storageClassName: gp2-multi-zone
        resources:
          requests:
            storage: 20Gi
# couchbase buckets to create
# disable default bucket creation by setting
# buckets.default: null
#
# setting default to null throws warning https://github.com/helm/helm/issues/5184
buckets:
  # A bucket to create by default
  default: null
  asset360:
    # Kind of bucket
    kind: CouchbaseBucket
    # Name of the bucket
    name: test
    # The amount of memory that should be allocated to the bucket
    memoryQuota: 1Gi
    # The number of bucket replicates
    replicas: 1
    # The priority when compared to other buckets
    ioPriority: high
    # The bucket eviction policy which determines behavior during expire and high mem usage
    evictionPolicy: valueOnly
    # The bucket's conflict resolution mechanism; which is to be used if a conflict occurs during Cross Data-Center Replication (XDCR). Sequence-based and timestamp-based mechanisms are supported.
    conflictResolution: seqno
    # The enable flush option denotes wether the data in the bucket can be flushed
    enableFlush: true
    # Enable Index replica specifies whether or not to enable view index replicas for this bucket.
    enableIndexReplica: false
    # data compression mode for the bucket to run in [off, passive, active]
    compressionMode: "passive"

# CouchbaseBackups runs a job which preserves data into backups
# backups:
#   default-backup:
#     name: full-incremental-backup
#     strategy: full_incremental
#     full:
#       schedule: "00 1 * * *"
#     incremental:
#       schedule: "30 * * * *"
#     successfulJobsHistoryLimit: 1
#     failedJobsHistoryLimit: 3
#     backOffLimit: 2
#     backupRetention: 168h   # 7 days on local disk
#     logRetention: 168h      # 7 days on local disk
#     size: 50Gi
#     s3bucket: REPLACEME
#     storageClassName: gp2-multi-data
