apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lrs-multi-zone
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
  fsType: xfs
